# Generated by Django 2.1.4 on 2019-03-08 09:09

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
            ],
        ),
    ]
