# Generated by Django 2.1.4 on 2019-03-08 10:36

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='名称')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='text',
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=50, verbose_name='项目名称'),
        ),
        migrations.AddField(
            model_name='item_process',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='items.Item', verbose_name='所属项目'),
        ),
    ]
