# Generated by Django 2.1.4 on 2019-02-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='fs',
            field=models.CharField(max_length=30, verbose_name='处理'),
        ),
    ]
