# Generated by Django 2.1.7 on 2019-02-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20190225_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='bz',
            field=models.BooleanField(default=False, verbose_name='报账'),
        ),
    ]
