# Generated by Django 2.1.4 on 2019-02-26 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('note', '0003_auto_20190225_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bz_dj', models.BooleanField(default=False, verbose_name='电教部报账权限')),
                ('bz_wl', models.BooleanField(default=False, verbose_name='网络信息部报账权限')),
                ('bz_jsj', models.BooleanField(default=False, verbose_name='计算机部报账权限')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
        ),
    ]
