# Generated by Django 2.1.4 on 2019-03-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0004_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'verbose_name': '权限', 'verbose_name_plural': '权限'},
        ),
    ]
